nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true
