import {stripIndent} from 'common-tags';

import {addNodeBundleInclusion} from '../tools/rollup';
import type {RollupNodeBundle} from '../tools/rollup';

import {
  MAGIC_MODULE_APP_ASSET_LOADER,
  MAGIC_MODULE_APP_COMPONENT,
} from '../constants';
import {createProjectPlugin, Runtime, TargetRuntime} from '../kit';
import type {
  App,
  ResolvedOptions,
  BuildOptionsForProject,
  ResolvedBuildProjectConfigurationHooks,
} from '../kit';

import type {EnvironmentOptions} from './magic-module-env';

export interface AppServerOptions {
  /**
   * The relative path to the module you want to use as the
   * entry for your app server. When provided, this completely
   * overwrites the default server content.
   *
   * @example './server'
   */
  entry: string;

  /**
   * Whether this server code uses the `http-handlers` library to
   * define itself in a generic way, which can be adapted to a variety
   * of environments. By default, this is `true`, and when `true`,
   * the `entry` you specified must export an `HttpHandler` object as
   * its default export. When set to `false`, the app server will be built
   * as a basic server-side JavaScript project, without the special
   * `http-handlers` adaptor.
   *
   * @default true
   */
  httpHandler?: boolean;

  /**
   * Whether the automatic server will serve assets for the browser build.
   * If this is `true`, you must ensure that your assets are stored in an
   * `assets` directory that is a sibling to the `server` directory that
   * will contain your server files. This is done automatically for you
   * with the default configuration applied by Quilt.
   *
   * @default true
   */
  serveAssets?: boolean;

  /**
   * Controls how the app server exposes environment variables.
   */
  env?: EnvironmentOptions;

  /**
   * Determines how dependencies will be bundled into your app server.
   * By default, Quilt will bundle all dependencies (other than node
   * built-in modules) into the build outputs, which optimizes for
   * performance. You can change this behavior by passing `false`,
   * which will force all dependencies to be resolved at runtime, or
   * by passing an object with granular controls on what dependencies
   * are bundled.
   */
  bundle?: boolean | RollupNodeBundle;
}

export interface AppServerConfigurationOptions {
  /**
   * Indicates that the app server build is being generated by Quilt.
   */
  quiltAppServer: boolean;
}

declare module '@quilted/sewing-kit' {
  interface BuildAppOptions extends AppServerConfigurationOptions {}
  interface DevelopAppOptions extends AppServerConfigurationOptions {}
}

const MAGIC_CUSTOM_SERVER_ENTRY_MODULE = '__quilt__/CustomAppServer';

export function appServer(options?: AppServerOptions) {
  return createProjectPlugin<App>({
    name: 'Quilt.App.Server',
    build({project, configure}) {
      configure(setupConfiguration(project, options));
    },
    develop({project, configure}) {
      configure(setupConfiguration(project, options) as any);
    },
  });
}

function setupConfiguration(project: App, options?: AppServerOptions) {
  const entry = options?.entry;
  const httpHandler = options?.httpHandler ?? true;
  const bundle = options?.bundle ?? true;
  const inlineEnv = options?.env?.inline;

  return (
    {
      runtime,
      rollupInput,
      rollupPlugins,
      rollupNodeBundle,
      quiltAppServerEntryContent,
      quiltHttpHandlerContent,
      quiltAsyncPreload,
      quiltAsyncManifest,
      quiltInlineEnvironmentVariables,
      quiltRuntimeEnvironmentVariables,
    }: ResolvedBuildProjectConfigurationHooks<App>,
    {quiltAppServer = false}: ResolvedOptions<BuildOptionsForProject<App>>,
  ) => {
    if (!quiltAppServer) return;

    if (inlineEnv != null && inlineEnv.length > 0) {
      quiltInlineEnvironmentVariables?.((variables) =>
        Array.from(new Set([...variables, ...inlineEnv])),
      );
    }

    quiltRuntimeEnvironmentVariables?.((runtime) => runtime ?? 'process.env');

    runtime(() => new TargetRuntime([Runtime.Node]));

    const content = entry
      ? httpHandler
        ? stripIndent`
          export {default} from ${JSON.stringify(
            project.fs.resolvePath(entry),
          )};
        `
        : stripIndent`
          import ${JSON.stringify(project.fs.resolvePath(entry))};
        `
      : stripIndent`
        import App from ${JSON.stringify(MAGIC_MODULE_APP_COMPONENT)};
        import assets from ${JSON.stringify(MAGIC_MODULE_APP_ASSET_LOADER)};
        import {createServerRenderingHttpHandler} from '@quilted/quilt/server';
  
        export default createServerRenderingHttpHandler(App, {
          assets,
        });
      `;

    quiltAsyncPreload?.(() => false);
    quiltAsyncManifest?.(() => false);

    rollupNodeBundle?.(() => {
      return addNodeBundleInclusion(
        /@quilted[/]quilt[/](magic|env|polyfills)/,
        bundle,
      );
    });

    rollupPlugins?.(async (plugins) => {
      const {cssRollupPlugin} = await import('./rollup/css');

      plugins.push(cssRollupPlugin({extract: false}));

      return plugins;
    });

    if (httpHandler) {
      quiltHttpHandlerContent?.(
        async () => await quiltAppServerEntryContent!.run(content),
      );
    } else {
      rollupInput?.(() => [MAGIC_CUSTOM_SERVER_ENTRY_MODULE]);
    }
  };
}
