export {
  Alternate,
  BodyAttributes,
  HTMLAttributes,
  Link,
  Meta,
  ThemeColor,
  Title,
  Favicon,
  useAlternateUrl,
  useBodyAttributes,
  useBrowserEffect,
  useCookie,
  useCookies,
  useHTMLAttributes,
  useInitialURL,
  useFavicon,
  useLink,
  useLocale,
  useMeta,
  useThemeColor,
  useTitle,
  type Cookies,
  type CookieOptions,
} from '@quilted/react-browser';

export {HTML} from './html/HTML.tsx';
