export {
  Alternate,
  BodyAttributes,
  HeadScript,
  HeadStyle,
  HTMLAttributes,
  Link,
  Meta,
  SearchRobots,
  Serialize,
  ThemeColor,
  Title,
  Viewport,
  Favicon,
  useAlternateUrl,
  useSerialized,
  useBodyAttributes,
  useHeadScript,
  useHeadStyle,
  useHTMLAttributes,
  useFavicon,
  useLink,
  useLocale,
  useMeta,
  useSearchRobots,
  useThemeColor,
  useTitle,
  useViewport,
  useHTMLUpdater,
  getSerialized,
} from '@quilted/react-html';
export type {Serializable} from '@quilted/react-html';
export {
  useCookie,
  useCookies,
  type Cookies,
  type CookieOptions,
} from '@quilted/react-http';

export {HTML} from './html/HTML.tsx';
