name: Prepare repo
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.1
    - uses: actions/setup-node@v2
      with:
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: pnpm install
      shell: bash
