name: Prepare repo
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.1
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
      shell: bash
