name: Prepare repo
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
    - uses: pnpm/action-setup@v2.2.1
      with:
        run_install: true
