import * as path from 'path';

import {stripIndent} from 'common-tags';
import {createProjectPlugin} from '@quilted/sewing-kit';
import type {App, WaterfallHook} from '@quilted/sewing-kit';
import type {ModuleFormat} from 'rollup';

import {
  PRELOAD_ALL_GLOBAL,
  MAGIC_MODULE_APP_ASSET_MANIFEST,
  MAGIC_MODULE_APP_COMPONENT,
} from '../constants';

import {STEP_NAME} from './app-build';

import {preloadAllGlobal} from './rollup/preload-all';

export interface AppServerOptions {
  /**
   * The relative path to the module you want to use as the
   * entry for your app server. When provided, this completely
   * overwrites the default server content.
   *
   * @example './server'
   */
  entry: string;

  /**
   * Whether this server code uses the `http-handlers` library to
   * define itself in a generic way, which can be adapted to a variety
   * of environments. By default, this is `true`, and when `true`,
   * the `entry` you specified must export an `HttpHandler` object as
   * its default export. When set to `false`, the app server will be built
   * as a basic server-side JavaScript project, without the special
   * `http-handlers` adaptor.
   */
  httpHandler?: boolean;
}

export interface AppServerBuildOptions {
  /**
   * Indicates that the app server build is being generated by Quilt.
   */
  quiltAppServer: boolean;
}

export interface AppServerHooks {
  /**
   * The content to use for the automatic application server. This
   * hook runs with the explicit content from the `server.entry` option,
   * or the default app server if that option is not set.
   */
  quiltAppServerEntryContent: WaterfallHook<string>;

  /**
   * The module format that will be used for the application server. By
   * default, this is set to `module`, which generates native ES module
   * outputs.
   */
  quiltAppServerOutputFormat: WaterfallHook<ModuleFormat>;

  /**
   * The port to run the automatic server on, if you use the default
   * Node server build (that is, you do not add any plugins that adapt
   * the server to a different environment, and you do not specify a
   * custom server with the `server.entry` option). This result is passed
   * to the `quiltHttpHandlerPort`, which may customize it further, before
   * falling back to the `PORT` environment if no explicit value is set.
   */
  quiltAppServerPort: WaterfallHook<number | undefined>;

  /**
   * The host to run the automatic server on, if you use the default
   * Node server build (that is, you do not add any plugins that adapt
   * the server to a different environment, and you do not specify a
   * custom server with the `server.entry` option). This result is passed
   * to the `quiltHttpHandlerHost`, which may customize it further.
   */
  quiltAppServerHost: WaterfallHook<string | undefined>;
}

declare module '@quilted/sewing-kit' {
  interface BuildAppOptions extends AppServerBuildOptions {}
  interface BuildAppConfigurationHooks extends AppServerHooks {}
}

const MAGIC_CUSTOM_SERVER_ENTRY_MODULE = '__quilt__/CustomAppServer';

export function appServer(options?: AppServerOptions) {
  const entry = options?.entry;
  const httpHandler = options?.httpHandler ?? true;

  return createProjectPlugin<App>({
    name: 'Quilt.App.Server',
    build({project, hooks, configure, run}) {
      hooks<AppServerHooks>(({waterfall}) => ({
        quiltAppServerHost: waterfall(),
        quiltAppServerPort: waterfall(),
        quiltAppServerOutputFormat: waterfall(),
        quiltAppServerEntryContent: waterfall(),
      }));

      configure(
        (
          {
            outputDirectory,
            rollupInput,
            rollupPlugins,
            rollupOutputs,
            rollupInputOptions,
            quiltAppServerHost,
            quiltAppServerPort,
            quiltAppServerEntryContent,
            quiltAppServerOutputFormat,
            quiltHttpHandlerHost,
            quiltHttpHandlerPort,
            quiltHttpHandlerContent,
            quiltAsyncPreload,
            quiltAsyncManifest,
          },
          {quiltAppServer = false},
        ) => {
          if (!quiltAppServer) return;

          const content = entry
            ? httpHandler
              ? stripIndent`
                  export {default} from ${JSON.stringify(
                    project.fs.resolvePath(entry),
                  )};
                `
              : stripIndent`
                  import ${JSON.stringify(project.fs.resolvePath(entry))};
                `
            : stripIndent`
                import '@quilted/quilt/global';
                import App from ${JSON.stringify(MAGIC_MODULE_APP_COMPONENT)};
                import assets from ${JSON.stringify(
                  MAGIC_MODULE_APP_ASSET_MANIFEST,
                )};
                import {createServerRenderingHttpHandler} from '@quilted/quilt/server';

                export default createServerRenderingHttpHandler(App, {
                  assets,
                  async before() {
                    await ${PRELOAD_ALL_GLOBAL};
                  },
                });
              `;

          quiltAsyncPreload?.(() => false);
          quiltAsyncManifest?.(() => false);

          rollupInputOptions?.((options) => {
            options.preserveEntrySignatures = false;
            return options;
          });

          rollupPlugins?.(async (plugins) => {
            const {cssRollupPlugin} = await import('./rollup/css');

            plugins.push(cssRollupPlugin({extract: false}));

            plugins.push({
              name: '@quilted/magic-module/asset-manifest',
              async resolveId(id) {
                if (id === MAGIC_MODULE_APP_ASSET_MANIFEST) return id;
                return null;
              },
              async load(source) {
                if (source !== MAGIC_MODULE_APP_ASSET_MANIFEST) return null;

                const manifestFiles = await project.fs.glob('manifest*.json', {
                  cwd: project.fs.buildPath('manifests'),
                  onlyFiles: true,
                });

                const manifests = (
                  await Promise.all(
                    manifestFiles.map(async (manifestFile) => {
                      const manifestString = await project.fs.read(
                        manifestFile,
                      );

                      return JSON.parse(manifestString);
                    }),
                  )
                ).sort(
                  (manifestA, manifestB) =>
                    (manifestA.metadata.priority ?? 0) -
                    (manifestB.metadata.priority ?? 0),
                );

                return stripIndent`
                  import {createAssetLoader} from '@quilted/async/server';

                  const manifests = JSON.parse(${JSON.stringify(
                    JSON.stringify(manifests),
                  )});

                  for (const manifest of manifests) {
                    manifest.metadata.browsers =
                      manifest.metadata.browsers
                        ? new RegExp(manifest.metadata.browsers)
                        : undefined;
                  }

                  // The default manifest is the last one, since it has the widest browser support.
                  const defaultManifest = manifests[manifests.length - 1];

                  const assetLoader = createAssetLoader({
                    async getManifest({userAgent}) {
                      // If there is no user agent, use the default manifest.
                      if (typeof userAgent !== 'string') return defaultManifest;

                      for (const manifest of manifests) {
                        if (manifest.metadata.browsers instanceof RegExp && manifest.metadata.browsers.test(userAgent)) {
                          return manifest;
                        }
                      }

                      return defaultManifest;
                    },
                  });

                  export default assetLoader;
                `;
              },
            });

            if (!httpHandler) {
              plugins.push({
                name: '@quilted/magic-app-server-custom-entry',
                resolveId(id) {
                  if (id === MAGIC_CUSTOM_SERVER_ENTRY_MODULE) {
                    return {id, moduleSideEffects: 'no-treeshake'};
                  }

                  return null;
                },
                load(source) {
                  if (source !== MAGIC_CUSTOM_SERVER_ENTRY_MODULE) return null;
                  return content;
                },
              });
            }

            plugins.push(preloadAllGlobal());

            return plugins;
          });

          rollupOutputs?.(async (outputs) => {
            const [format, outputRoot] = await Promise.all([
              quiltAppServerOutputFormat!.run('module'),
              outputDirectory.run(project.fs.buildPath()),
            ]);

            outputs.push({
              format,
              entryFileNames: 'index.js',
              dir: path.join(outputRoot, 'server'),
            });

            return outputs;
          });

          if (httpHandler) {
            quiltHttpHandlerHost?.(async () =>
              quiltAppServerHost!.run(undefined),
            );

            quiltHttpHandlerPort?.(async () =>
              quiltAppServerPort!.run(undefined),
            );

            quiltHttpHandlerContent?.(
              async () => await quiltAppServerEntryContent!.run(content),
            );
          } else {
            rollupInput?.(() => [MAGIC_CUSTOM_SERVER_ENTRY_MODULE]);
          }
        },
      );

      run((step, {configuration}) =>
        step({
          name: 'Quilt.App.Server',
          label: `Build automatic server for app ${project.name}`,
          needs: (step) => {
            return {
              need: step.target === project && step.name === STEP_NAME,
              allowSkip: true,
            };
          },
          async run() {
            const [configure, {buildWithRollup}] = await Promise.all([
              configuration({
                quiltAppServer: true,
                quiltHttpHandler: httpHandler,
              }),
              import('@quilted/sewing-kit-rollup'),
            ]);

            await buildWithRollup(configure);
          },
        }),
      );
    },
  });
}
