import type {GetModuleInfo, GetManualChunk} from 'rollup';
import type {Config as BrowserslistConfig} from 'browserslist';
import {stripIndent} from 'common-tags';

import {createProjectPlugin, TargetRuntime, Runtime} from '@quilted/sewing-kit';
import type {
  App,
  WaterfallHook,
  WaterfallHookWithDefault,
} from '@quilted/sewing-kit';

import type {} from '@quilted/async/sewing-kit';

import {MAGIC_MODULE_APP_COMPONENT} from '../constants';

export interface AssetOptions {
  minify: boolean;
  baseUrl: string;
}

export interface Options {
  assets: AssetOptions;
}

export interface AppBuildHooks {
  quiltAssetBaseUrl: WaterfallHookWithDefault<string>;
  quiltBrowserEntryShouldHydrate: WaterfallHook<boolean>;
  quiltBrowserEntryContent: WaterfallHookWithDefault<string | undefined>;
}

const BROWSERSLIST_MODULES_QUERY =
  'extends @quilted/browserslist-config/modules';

const DEFAULT_BROWSERSLIST_CONFIG: BrowserslistConfig = {
  defaults: ['extends @quilted/browserslist-config/defaults'],
  modules: [BROWSERSLIST_MODULES_QUERY],
  evergreen: ['extends @quilted/browserslist-config/evergreen'],
};

export interface BrowserTarget {
  name: string;
  priority: number;
  targets: string[];
}

export interface QuiltMetadata {
  /**
   * The source for a regular expression that matches the useragent
   * string of the target browsers for this build.
   */
  browsers: string;

  /**
   * The priority to use for this manifest. The priority is used at
   * runtime by quilt to determine the order in which to test manifests
   * against the browser targets for the bundle, which allows quilt to
   * select the "best" (typically, that means smallest) bundle.
   */
  priority: number;
}

declare module '@quilted/sewing-kit' {
  interface BuildAppOptions {
    /**
     * Indicates that the base build is being generated by `quilt`.
     */
    quiltApp: boolean;

    /**
     * The selected browserslist configuration for this build.
     */
    quiltBrowserTargets: BrowserTarget;
  }

  interface BuildAppConfigurationHooks extends AppBuildHooks {}
}

const MAGIC_ENTRY_MODULE = '__quilt__/AppEntry.tsx';
export const STEP_NAME = 'Quilt.App.Build';

export function appBuild({assets}: Options) {
  return createProjectPlugin<App>({
    name: STEP_NAME,
    build({project, hooks, configure, run}) {
      hooks<AppBuildHooks>(({waterfall}) => ({
        quiltAssetBaseUrl: waterfall({
          default: assets.baseUrl,
        }),
        quiltBrowserEntryContent: waterfall<string | undefined>({
          default: undefined,
        }),
        quiltBrowserEntryShouldHydrate: waterfall(),
      }));

      configure(
        (
          {
            runtime,
            targets,
            outputDirectory,
            rollupInput,
            rollupInputOptions,
            rollupOutputs,
            rollupPlugins,
            quiltAsyncManifestPath,
            quiltAsyncManifestMetadata,
            quiltAssetBaseUrl,
            quiltAsyncAssetBaseUrl,
            quiltBrowserEntryContent,
            quiltBrowserEntryShouldHydrate,
          },
          options,
        ) => {
          if (!options.quiltApp) return;

          runtime(() => new TargetRuntime([Runtime.Browser]));

          const browserTargets = options.quiltBrowserTargets;
          const targetFilenamePart = browserTargets
            ? `.${browserTargets.name}`
            : '';

          if (browserTargets) {
            targets?.(() => browserTargets.targets);

            quiltAsyncManifestMetadata?.(async (metadata) => {
              const {getUserAgentRegExp} = await import(
                'browserslist-useragent-regexp'
              );

              Object.assign(metadata, {
                priority: browserTargets.priority,
                browsers: getUserAgentRegExp({
                  browsers: browserTargets.targets,
                  ignoreMinor: true,
                  ignorePatch: true,
                  allowHigherVersions: true,
                }).source,
              } as QuiltMetadata);

              return metadata;
            });
          }

          quiltAsyncAssetBaseUrl?.(() => quiltAssetBaseUrl!.run());

          quiltAsyncManifestPath?.(() =>
            project.fs.buildPath(
              `manifests/manifest${targetFilenamePart}.json`,
            ),
          );

          rollupInput?.(() => [MAGIC_ENTRY_MODULE]);

          rollupInputOptions?.((options) => {
            options.preserveEntrySignatures = false;
            return options;
          });

          rollupPlugins?.(async (plugins) => {
            const [{cssRollupPlugin}, {systemJs}] = await Promise.all([
              import('./rollup/css'),
              import('./rollup/system-js'),
            ]);

            plugins.push(
              systemJs({minify: assets.minify}),
              cssRollupPlugin({
                minify: assets.minify,
                extract: true,
              }),
            );

            plugins.push({
              name: '@quilted/app/magic-entry',
              async resolveId(id) {
                if (id === MAGIC_ENTRY_MODULE) return id;
                return null;
              },
              async load(source) {
                if (source !== MAGIC_ENTRY_MODULE) return null;

                const content = await quiltBrowserEntryContent!.run();

                if (content) return content;

                const shouldHydrate = await quiltBrowserEntryShouldHydrate!.run(
                  true,
                );

                const reactFunction = shouldHydrate ? 'hydrate' : 'render';

                return {
                  code: stripIndent`
                    import '@quilted/quilt/global';
                    import {${reactFunction}} from 'react-dom';
                    import App from ${JSON.stringify(
                      MAGIC_MODULE_APP_COMPONENT,
                    )};
      
                    ${reactFunction}(<App />, document.getElementById('app'));
                  `,
                  moduleSideEffects: 'no-treeshake',
                };
              },
            });

            if (assets.minify) {
              const {terser} = await import('rollup-plugin-terser');
              plugins.push(terser({safari10: true, compress: true}));
            }

            return plugins;
          });

          rollupOutputs?.(async (outputs) => {
            const [dir, isESM] = await Promise.all([
              outputDirectory.run(project.fs.buildPath('assets')),
              browserTargets
                ? targetsSupportModules(browserTargets.targets)
                : Promise.resolve(true),
            ]);

            outputs.push({
              format: isESM ? 'esm' : 'systemjs',
              dir,
              entryFileNames: `app${targetFilenamePart}.[hash].js`,
              assetFileNames: `[name]${targetFilenamePart}.[hash].[ext]`,
              chunkFileNames: `[name]${targetFilenamePart}.[hash].js`,
              manualChunks: createManualChunksSorter(),
            });

            return outputs;
          });
        },
      );

      run(async (step, {configuration}) => {
        const steps: ReturnType<typeof step>[] = [];

        const {default: browserslist} = await import('browserslist');

        const foundConfig =
          browserslist.findConfig(project.root) ?? DEFAULT_BROWSERSLIST_CONFIG;

        const browserslistConfig: Record<string, string[]> = {};

        for (const [name, query] of Object.entries(foundConfig)) {
          browserslistConfig[name] = browserslist(query);
        }

        // We assume that the smallest set of browser targets is the highest priority,
        // since that usually means that the bundle sizes will be smaller.
        const targetsBySize = Object.values(browserslistConfig).sort(
          (targetsA, targetsB) => {
            return (targetsA?.length ?? 0) - (targetsB?.length ?? 0);
          },
        );

        for (const [name, targets] of Object.entries(browserslistConfig)) {
          if (targets == null || targets.length === 0) continue;

          const normalizedName = name === 'defaults' ? 'default' : name;

          steps.push(
            step({
              name: STEP_NAME,
              label: `Build app ${project.name} (browser targets: ${normalizedName})`,
              async run() {
                const [configure, {buildWithRollup}] = await Promise.all([
                  configuration({
                    quiltApp: true,
                    quiltBrowserTargets: {
                      name: normalizedName,
                      targets,
                      priority: targetsBySize.indexOf(targets),
                    },
                  }),
                  import('@quilted/sewing-kit-rollup'),
                ]);

                await buildWithRollup(configure);
              },
            }),
          );
        }

        return steps;
      });
    },
  });
}

let esmBrowserslist: Set<string>;

async function targetsSupportModules(targets: string[]) {
  if (esmBrowserslist == null) {
    const {default: browserslist} = await import('browserslist');

    esmBrowserslist = new Set(browserslist(BROWSERSLIST_MODULES_QUERY));
  }

  return targets.every((target) => esmBrowserslist.has(target));
}

const FRAMEWORK_CHUNK_NAME = 'framework';
const VENDOR_CHUNK_NAME = 'vendor';
const FRAMEWORK_TEST_STRINGS = [
  '/node_modules/preact/',
  '/node_modules/react/',
  '/node_modules/@quilted/',
];

// When building from source, quilt packages are not in node_modules,
// so we instead add their repo paths to the list of framework test strings.
if (process.env.SEWING_KIT_FROM_SOURCE) {
  FRAMEWORK_TEST_STRINGS.push('/quilt/packages/');
}

interface ImportMetadata {
  fromEntry: boolean;
  fromFramework: boolean;
}

// Inspired by Vite: https://github.com/vitejs/vite/blob/c69f83615292953d40f07b1178d1ed1d72abe695/packages/vite/src/node/build.ts#L567
function createManualChunksSorter(): GetManualChunk {
  const cache = new Map<string, ImportMetadata>();

  return (id, {getModuleInfo}) => {
    if (
      !id.includes('node_modules') &&
      !FRAMEWORK_TEST_STRINGS.some((test) => id.includes(test))
    ) {
      return;
    }

    if (id.endsWith('.css')) return;

    const importMetadata = getImportMetadata(id, getModuleInfo, cache);

    if (!importMetadata.fromEntry) return;

    if (importMetadata.fromFramework) {
      return FRAMEWORK_CHUNK_NAME;
    }

    return VENDOR_CHUNK_NAME;
  };
}

function getImportMetadata(
  id: string,
  getModuleInfo: GetModuleInfo,
  cache: Map<string, ImportMetadata>,
  importStack: string[] = [],
): ImportMetadata {
  if (cache.has(id)) return cache.get(id)!;

  if (importStack.includes(id)) {
    // circular dependencies
    const result = {fromEntry: false, fromFramework: false};
    cache.set(id, result);
    return result;
  }

  const module = getModuleInfo(id);

  if (!module) {
    const result = {fromEntry: false, fromFramework: false};
    cache.set(id, result);
    return result;
  }

  if (module.isEntry) {
    const result = {fromEntry: true, fromFramework: false};
    cache.set(id, result);
    return result;
  }

  const newImportStack = [...importStack, id];
  const importersMetadata = module.importers.map((importer) =>
    getImportMetadata(importer, getModuleInfo, cache, newImportStack),
  );

  const result = {
    fromEntry: importersMetadata.some(({fromEntry}) => fromEntry),
    fromFramework:
      FRAMEWORK_TEST_STRINGS.some((test) => id.includes(test)) ||
      importersMetadata.some((importer) => importer.fromFramework),
  };

  cache.set(id, result);
  return result;
}
