name: CI

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_call:
    inputs:
      build:
        type: boolean
        default: true
        description: 'Whether to run a build as part of testing'

jobs:
  lint:
    name: Lint 💅
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-lint@v2

  type-check:
    name: Type check 🧮
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-type-check@v2

  unit-tests:
    name: Unit tests 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-test@v2

  build:
    name: Build 🏗
    if: ${{ inputs.build || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-build@v2
