name: Type Check with cache
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      id: typescript-cache
      with:
        path: |
          **/build/typescript/
          **/*.tsbuildinfo
        key: typescript-cache-v2-${{ github.sha }}
        restore-keys: typescript-cache-v2-
    - run: pnpm run type-check
      shell: bash
